export const TABLES = {
  AGENCY_USERS: "agency_users",
  AGENCIES: "agencies",
  CARER_HOUSEHOLDS: "carer_households",
  HOUSEHOLD_CARERS: "household_carers",
  HOUSEHOLD_CHILDREN: "household_children",
  CHILDREN: "children",
  PLACEMENT_TYPES: "placement_types",
  BIOLOGICAL_PARENT_PLACEMENTS: "biological_parent_placements",
  CHILD_BIOLOGICAL_PARENTS: "child_biological_parents",
  CHILD_ALLERGIES: "child_allergies",
  CHILD_MEDICAL_CONDITIONS: "child_medical_conditions",
  CHILD_EMERGENCY_CONTACTS: "child_emergency_contacts",
  CHILD_PROFESSIONAL_CONTACTS: "child_professional_contacts",
} as const;
