export const TABLES = {
  AGENCY_USERS: "agency_users",
  AGENCIES: "agencies",
  CARER_HOUSEHOLDS: "carer_households",
  HOUSEHOLD_CARERS: "household_carers",
  HOUSEHOLD_CHILDREN: "household_children",
  CHILDREN: "children",
  PLACEMENT_TYPES: "placement_types",
  BIOLOGICAL_PARENT_PLACEMENTS: "biological_parent_placements",
  CHILD_BIOLOGICAL_PARENTS: "child_biological_parents",
  CHILD_ALLERGIES: "child_allergies",
  CHILD_MEDICAL_CONDITIONS: "child_medical_conditions",
  CHILD_EMERGENCY_CONTACTS: "child_emergency_contacts",
  CHILD_PROFESSIONAL_CONTACTS: "child_professional_contacts",

  DAILY_LOG_ASSIGNMENTS: "daily_log_assignments",
  DAILY_LOGS: "daily_logs",
  DAILY_LOG_TEMPLATES: "daily_log_templates",
  DAILY_LOG_CONTRIBUTORS: "daily_log_contributors",

  GLOBAL_USER_ROLES: "global_user_roles",
  LICENCE_TYPES: "licence_types",
  TENANT_LICENCES: "tenant_licences",
  INVOICES: "invoices",
  BILLING_CUSTOMERS: "billing_customers",
  BILLING_PAYMENT_METHODS: "billing_payment_methods",
  BILLING_SUBSCRIPTIONS: "billing_subscriptions",
  BILLING_EVENTS: "billing_events",
  BILLING_SEAT_CHANGES: "billing_seat_changes",
} as const;
