import type { FastifyInstance } from "fastify";
import { healthRoute } from "./health.js";
import { profileRoute } from "./profile.js";
import { childrenRoute } from "./children.js";
import { dailyLogsRoute } from "./daily-logs.js";
import { dailyLogCatalogRoute } from "./daily-log-catalog.js";
import { filesRoute } from "./files.js";
import { figChatRoute } from "./figchat.js";
import { lifeStoryRoute } from "./life-story.js";
import { billingRoute } from "./billing.js";
import { billingCollectRoute } from "./internal-billing.js";
import { dailyLogRemindersRoute } from "./internal-daily-log-reminders.js";
import { gocardlessWebhookRoute } from "./webhooks-gocardless.js";
import { calendarRoute } from "./calendar.js";
import { documentsRoute } from "./documents.js";
import { householdsRoute } from "./households.js";
import { placementsRoute } from "./placements.js";
import { ticketsRoute } from "./tickets.js";
import { surveysRoute } from "./surveys.js";
import { expensesRoute } from "./expenses.js";
import { authRoute } from "./auth.js";
import { accountRoute } from "./account.js";
import { gdprConsentRoute } from "./gdpr-consent.js";
import { notificationsRoute } from "./notifications.js";
import { fcmRoute } from "./fcm.js";

export async function registerRoutes(app: FastifyInstance) {
  await app.register(healthRoute);
  await app.register(authRoute);
  await app.register(gocardlessWebhookRoute);
  await app.register(billingCollectRoute);
  await app.register(dailyLogRemindersRoute);
  await app.register(profileRoute);
  await app.register(accountRoute);
  await app.register(gdprConsentRoute);
  await app.register(notificationsRoute);
  await app.register(fcmRoute);
  await app.register(childrenRoute);
  await app.register(dailyLogsRoute);
  await app.register(dailyLogCatalogRoute);
  await app.register(filesRoute);
  await app.register(figChatRoute);
  await app.register(lifeStoryRoute);
  await app.register(billingRoute);
  await app.register(calendarRoute);
  await app.register(documentsRoute);
  await app.register(householdsRoute);
  await app.register(placementsRoute);
  await app.register(ticketsRoute);
  await app.register(surveysRoute);
  await app.register(expensesRoute);
}
